name: CI/CD 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run-unit-test:
    name: Build and run unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Run unit tests
      run: npm run test:unit
  deploy:
    name: Deploy to production
    needs: build-and-run-unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Render Deployment
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
  build-and-run-ui-test:
    name: Build and run UI tests
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Install playwright
      run:  npx playwright install
    - name: Run ui tests
      run: npm run test:ui

